Usuarios/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('landing_admin/<int:usuario_id>/<int:isAdmin>/', views.menu, name='landing_admin'),

    path('cursos_admin/<int:usuario_id>/', views.cursos_admin, name='cursos_admin'),

    path('cursos_admin_create/<int:usuario_id>/<int:id_curso>/', views.cursos_admin_create, name='cursos_admin_create'),
    path('cursos_admin_delete/<int:usuario_id>/<int:id_curso>/', views.cursos_admin_delete, name='cursos_admin_delete'),
    path('evaluaciones_admin/<int:usuario_id>/<int:isAdmin>/', views.evaluaciones_admin, name='evaluaciones_admin'),
    path('evaluaciones_admin_ver/<int:usuario_id>/<str:rubrica_name>/<int:isAdmin>/', views.evaluaciones_admin_ver,
         name='evaluaciones_admin_ver'),

    path('evaluaciones_admin_create/<int:usuario_id>/', views.evaluaciones_admin_create, name='evaluaciones_admin_create'),
    path('evaluadores_admin/<int:usuario_id>/', views.evaluadores_admin, name='evaluadores_admin'),

    path('evaluadores_admin_edit/<int:usuario_id>/<int:eval_id>/', views.evaluadores_admin_edit, name='evaluadores_admin_edit'),
    path('evaluadores_admin_delete/<int:usuario_id>/<int:eval_id>/', views.evaluadores_admin_delete, name='evaluadores_admin_delete'),

    path('rubricas_admin/<int:usuario_id>/', views.rubricas_admin, name='rubricas_admin'),
    path('rubricas_admin_create/<int:usuario_id>/', views.rubricas_admin_create, name='rubricas_admin_create'),
    path('rubricas_admin_ver/<int:usuario_id>/<str:rubricaName>', views.rubricas_admin_ver, name='rubricas_admin_ver'),

    path('rubricas_admin_eliminar/<int:usuario_id>/<str:rubricaName>', views.rubricas_admin_eliminar, name='rubricas_admin_eliminar'),

    # para registrarse
    path('registro/', views.registro, name='registro'),
]

swjjRubricas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(('Usuarios.urls', 'Usuarios'), namespace='usuarios')),
    path('admin/', admin.site.urls),
]

Usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Usuario_admin(models.Model):
    name = models.CharField(max_length=200)
    app_paterno = models.CharField(max_length=50, blank=True, null=True)
    app_materno = models.CharField(max_length=50, blank=True, null=True)
    isAdmin = models.BooleanField(default=True)
    password = models.CharField(max_length=50)

class Usuario_evaluador(models.Model):
    name = models.CharField(max_length=200)
    app_paterno = models.CharField(max_length=50, blank=True, null=True)
    app_materno = models.CharField(max_length=50, blank=True, null=True)
    correo = models.EmailField(max_length=100)
    isAdmin = models.BooleanField(default=False)
    password = models.CharField(max_length=50) # TODO : Remember to randomize
    myAdminID = models.ForeignKey(Usuario_admin,on_delete=models.CASCADE)

    class Meta:
        unique_together = ('correo',)

    def __str__(self):
        return self.name

class Course(models.Model):
    nombreCurso = models.CharField(max_length=250, help_text='Nombre del curso ')
    codigoCurso = models.CharField(max_length=8, help_text='Codigo curso ')
    numSeccionCurso = models.IntegerField(help_text='Numero seccion del curso')
    anioCurso = models.IntegerField(help_text='Año del curso ')
    semesterCurso = models.IntegerField(help_text='Semestre ')

    class Meta:
        unique_together = ('codigoCurso', 'numSeccionCurso', 'anioCurso' ,'semesterCurso',)

    def __str__(self):
        return self.nombreCurso

class Grupo(models.Model):
    nombreGrupo = models.CharField(max_length=200)
    cursoGrupo = models.ForeignKey(Course,on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreGrupo

class Alumno(models.Model):
    nombreAlumno = models.CharField(max_length=200)
    hasPresented = models.BooleanField(default=False) # Agregado
    grupoAsociado = models.ForeignKey(Grupo,on_delete=models.DO_NOTHING) # TODO: Es buena idea doNothing?
    cursoAsociado = models.ForeignKey(Course,on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreAlumno

class Rubrica(models.Model):
    nombre: object = models.CharField(max_length=100)
    duracion_minima = models.TimeField(u"Duración Mínima")
    duracion_maxima = models.TimeField(u"Duración Máxima")
    dataTable = models.FilePathField(path='./RubricasDataTables')


    def __str__(self):
        return self.nombre

    def get_criterios(self):
        """
        Gets all criterios of this rubrica
        :return: a list of Criterio
        """
        return Criterio.objects.filter(rubrica__nombre=self.nombre)

class Evaluacion(models.Model):
    nombre: object = models.CharField(max_length=100)
    curso = models.ForeignKey(Course,on_delete=models.CASCADE)
    equipo = models.ForeignKey(Grupo,on_delete=models.CASCADE) # TODO : Deberia ser do nothing
    rubrica = models.ForeignKey(Rubrica,on_delete=models.CASCADE)
    # evaluadores = models.ManyToManyField(Usuario_evaluador, null=True) # NOT NULL constraint failed

    def __str__(self):
        return self.nombre

class EvaluacionAsignada(models.Model):
    evaluador = models.ManyToManyField(Usuario_evaluador)


class Criterio(models.Model):
    rubrica = models.ForeignKey(Rubrica, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    def get_puntajes(self):
        """
        Gets all puntaje that belong to this criterio
        :return: a list of Puntaje
        """
        return Puntaje.objects.filters(criterio__nombre=self.nombre)


class Puntaje(models.Model):
    criterio = models.ForeignKey(Criterio, on_delete=models.CASCADE)
    puntaje = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    texto = models.CharField(max_length=200)

    def __str__(self):
        return self.texto

Usuarios/views.py
from django.shortcuts import render

# tal vez deba borrar algunas de estas
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import redirect # Added
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
##

# formularios

from .forms import RegistroUsuarioForm, RegistroEvaluadorForm, NuevaEvaluacion
from .forms import NuevoCurso
from .forms import NuevoEvaluador
from .forms import NuevaRubrica
##
from .models import Usuario_admin, Course, Rubrica, Criterio, Puntaje, Usuario_evaluador
import csv

##para el json
import json


##
def login(request):
    if request.POST:
        username = request.POST.get('usuario')
        password = request.POST.get('password')

        # Verificar si es admin
        if (Usuario_admin.objects.filter(name=username, password=password).exists()):
            user = Usuario_admin.objects.get(name=username, password=password)
            return menu(request,user.id,user.isAdmin)

        if (Usuario_evaluador.objects.filter(correo=username, password=password).exists()):
            user = Usuario_evaluador.objects.get(correo=username, password=password)
            return menu(request,user.id,user.isAdmin)

    return render(request, 'Usuarios/login.html')


def courses(request):
    listaCursos = Course.objects.all()
    return listaCursos


def menu(request, usuario_id,isAdmin):
    # aca deberia haccerse la autenticaciondel usuario.
    if isAdmin==1:
        usuario = Usuario_admin.objects.get(pk=usuario_id)
    else:
        usuario= Usuario_evaluador.objects.get(pk=usuario_id)

    return render(request, 'Usuarios/Admin/Landing_admin.html', {'usuario': usuario})


def cursos_admin(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)

    if request.POST:
        form = NuevoCurso(request.POST, request.FILES)
        if form.is_valid():  # si no no crea los cleaned data
            form.save()

    listaCursos = courses(request)
    form = NuevoCurso()

    # le paso el form, nuevo_curso a la página.
    return render(request, 'Usuarios/Admin/Cursos_admin.html',
                  {'usuario': usuario, 'nuevo_curso': form, 'listaCursos': listaCursos})

# TODO : Se encarga de editar o realizar update, ignorar nombre
def cursos_admin_create(request, usuario_id, id_curso):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    curso = Course.objects.get(id=id_curso)
    if request.method == 'GET':
        form = NuevoCurso(instance=curso)
    else:
        form = NuevoCurso(request.POST, request.FILES ,instance=curso)
        if form.is_valid():
            form.save()
        #return redirect('usuarios:cursos_admin', {'usuario' : usuario})
        # SOL : https://stackoverflow.com/questions/13202385/django-reverse-with-arguments-and-keyword-arguments-not-found
        return redirect(reverse('usuarios:cursos_admin',kwargs={'usuario_id' : usuario_id})) # Funciona
    return render(request,'Usuarios/Admin/Cursos_admin_create.html',{'form' : form, 'usuario': usuario, 'curso': curso})

def cursos_admin_delete(request, usuario_id, id_curso):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    curso = Course.objects.get(id = id_curso)
    if request.method == 'POST':
        curso.delete()
        #return redirect('usuarios:cursos_admin')
        return redirect(reverse('usuarios:cursos_admin', kwargs={'usuario_id': usuario_id})) # Funciona
    return render(request, 'Usuarios/Admin/Cursos_admin_delete.html', {'usuario': usuario ,'curso' : curso})

def evaluaciones_admin(request, usuario_id,isAdmin):
    if isAdmin==1:
        usuario = Usuario_admin.objects.get(pk=usuario_id)
    else:
        usuario = Usuario_evaluador.objects.get(pk=usuario_id)



    #esta parte esta harcodeada, pero se deberia arreglar, cuando el modelo Evaluacion este listo
    listaEval = []
    listaEval.append("tarea1")
    listaEval.append("tarea2")




    return render(request, 'Usuarios/Admin/Evaluaciones_admin.html', {'usuario': usuario,'listaEval':listaEval})


def evaluaciones_admin_ver(request, usuario_id,rubrica_name, isAdmin):
    if isAdmin == 1:
        usuario = Usuario_admin.objects.get(pk=usuario_id)

        with open('rubricaJson.json', 'r') as f:
            data = json.load(f)

        if data:
            if str(usuario_id) in data:
                j = data[str(usuario_id)][rubrica_name]
                matriz = parseJsonToMatriz(j, int(j.get("numFilas")), int(j.get("numColumnas")))
                print(j.get("numColumnas"))

    else:
        usuario = Usuario_evaluador.objects.get(pk=usuario_id)

        with open('rubricaJson.json', 'r') as f:
            data = json.load(f)

        if data:
            if str(usuario.myAdminID.id) in data:
                j = data[str(usuario.myAdminID.id)][rubrica_name]
                matriz = parseJsonToMatriz(j, int(j.get("numFilas")), int(j.get("numColumnas")))
                print(j.get("numColumnas"))

    return render(request, 'Usuarios/Admin/Evaluaciones_admin_ver.html', {'usuario': usuario,'rubrica':j,'matriz':matriz,'rangeCol':range(int(j.get("numColumnas"))-1)})


def evaluaciones_admin_create(request, usuario_id): # TODO: Complete
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    if request.POST:
        form = NuevaEvaluacion(request.POST, request.FILES)
        if form.is_valid():
            # listaDeEvaluadores = form.cleaned_data.get('evaluadores')
            form.save()
    form = NuevaEvaluacion()
    return render(request, 'Usuarios/Admin/Evaluaciones_admin_create.html', {'usuario': usuario, 'nueva_eval': form})


def evaluadoresReq(request):
    listaEvaluadores = Usuario_evaluador.objects.all()
    return listaEvaluadores


def evaluadores_admin(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)

    if request.POST:
        form = RegistroEvaluadorForm(request.POST, request.FILES)
        if form.is_valid():  # si no no crea los cleaned data
            form.save(usuario_id)  # por el override, ver forms

    listaEvaluadores = evaluadoresReq(request)
    form = RegistroEvaluadorForm()

    # le paso el form, nuevo_curso a la página.
    return render(request, 'Usuarios/Admin/Evaluadores_admin.html', {'usuario': usuario, 'nuevo_evaluador': form,
                                                                     'listaEval': listaEvaluadores})


#def evaluadores_admin_edit(request, usuario_id):
#    usuario = Usuario_admin.objects.get(pk=usuario_id)
#    return render(request, 'Usuarios/Admin/Evaluadores_admin_edit.html', {'usuario': usuario})

def evaluadores_admin_edit(request, usuario_id, eval_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    evaluador = Usuario_evaluador.objects.get(id=eval_id)
    if request.method == 'GET':
        form = RegistroEvaluadorForm(instance=evaluador)
    else:
        form = RegistroEvaluadorForm(request.POST, request.FILES ,instance=evaluador)
        if form.is_valid():
            form.save(usuario_id, evaluador) # Literalmente envia el objeto
        #return redirect('usuarios:cursos_admin', {'usuario' : usuario})
        # SOL : https://stackoverflow.com/questions/13202385/django-reverse-with-arguments-and-keyword-arguments-not-found
        return redirect(reverse('usuarios:evaluadores_admin',kwargs={'usuario_id' : usuario_id})) # Funciona
    return render(request,'Usuarios/Admin/Evaluadores_admin_edit.html',{'form' : form, 'usuario': usuario, 'eval': evaluador})


#def evaluadores_admin_delete(request, usuario_id):
#    usuario = Usuario_admin.objects.get(pk=usuario_id)
#    return render(request, 'Usuarios/Admin/Evaluadores_admin_delete.html', {'usuario': usuario})

def evaluadores_admin_delete(request, usuario_id, eval_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    evaluador = Usuario_evaluador.objects.get(id=eval_id)
    if request.method == 'POST':
        evaluador.delete()
        #return redirect('usuarios:cursos_admin')
        return redirect(reverse('usuarios:evaluadores_admin',kwargs={'usuario_id' : usuario_id})) # Funciona
    return render(request, 'Usuarios/Admin/Evaluadores_admin_delete.html', {'usuario': usuario ,'eval': evaluador})


# Commit 15.05

def rubricas_admin(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)

    # Primero que nada, guardar una nueva rubrica
    if request.POST:
        form = NuevaRubrica(request.POST, request.FILES)

        new_rubrica = form.save(request.POST, usuario_id)
        print("rubrica guardada con exito")

    with open('rubricaJson.json', 'r') as f:
        data = json.load(f)


    rubricsNames = []
    if data:
        if str(usuario_id) in data:
            for key in data[str(usuario_id)]:
                rubricsNames.append(key)
    print(rubricsNames)

    return render(request, 'Usuarios/Admin/Rubricas_admin.html', {'usuario': usuario, 'rubricsNames': rubricsNames})


def rubricas_admin_create(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    # Esta es
#   Esto ahora se encuentra en rubricas_admin
#    if request.POST:
#        form = NuevaRubrica(request.POST, request.FILES)#
#
#        if form.is_valid():
#           new_rubrica = form.save(request.POST, usuario_id)
#            print("rubrica guardada con exito")
#        else:
#            print("Hay datos incorrectos")
#            return render(request, 'Usuarios/Admin/Rubricas_admin_create.html', {'usuario': usuario, 'nueva_rubrica': form})

    form = NuevaRubrica()

    return render(request, 'Usuarios/Admin/Rubricas_admin_create.html', {'usuario': usuario, 'nueva_rubrica': form})


# para el registro
def registro(request):
    if request.POST:
        form = RegistroUsuarioForm(request.POST, request.FILES)

        if form.is_valid():
            new_admin = form.save()
            return menu(request, new_admin.id, new_admin.isAdmin)

templates/Usuarios/Admin/Cursos_admin.html
{% extends 'Usuarios/menuAdmin.html' %}

{%block page %}
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

      <!-- Portada -->
      <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
        <h2 class="w3-xxlarge w3-text-red"><b>Cursos</b></h2>
        <hr style="width:50px;border:5px solid red" class="w3-round">
        <p><h4>Seleccione un curso</h4>
      </div>

    <!--Cajas cursos-->
    <!--
    <div class="w3-row-padding w3-center w3-margin-top">
        <div class="w3-quarter w3-margin-top">
            <button onclick="document.getElementById('gestionar').style.display='block'"
                    class="w3-card w3-container w3-hover-shadow w3-light-gray" style="max-height:380px;min-height:317px">
                <span style="font-size:22px">Ingeniería de Software</span><br>
                <i class="fas fa-book" style="font-size:100px"></i><br>
                <span style="font-size:20px">CC4401-1</span><br>
                <span style="font-size:18px">Primavera 2019</span>
                <br>
                <span class="w3-btn w3-red" onclick="alert('Dude, estás editando!')">
                    <i class="fas fa-edit"></i>
                </span>
                <!-- Separar los botones un poco?-->
                <!--
                <span class="w3-btn w3-red" onclick="alert('Calmao, estás seguro de que vas a borrar esto?')">
                    <i class="fas fa-trash-alt"></i>
                </span>
            </button>
        </div>-->

<!-- Si la lista de cursos no es vacía, se itera-->
    {% if listaCursos %}
    {%  for curso in listaCursos %}
      <!--Caja Ejemplo -->
        <!-- El orden y margen esta dado por la class-->
        <div class="w3-quarter w3-margin-top w3-center w3-margin">
            <button {% comment %}onclick="document.getElementById('gestionar').style.display='block'" {% endcomment %}class="w3-card w3-container w3-hover-shadow w3-light-gray" style="min-height:317px">

                <h3>Nombre de curso</h3>
                    {{ curso.nombreCurso }}<br>
                <i class="fas fa-book" style="font-size:100px"></i>
                <p>Código</p>
                    {{ curso.codigoCurso }}
                <p>Sección</p>
                    {{ curso.numSeccionCurso }}
                <p>Semestre y año </p>
                    {{ curso.semesterCurso }} - {{ curso.anioCurso }}
                <!-- Patron para llamar de algo de django (back end) es con dos curly braces -->
            </button>
            <!-- Es un button por iteracion anterior no tiene funcionamiento-->
            <div id="botonera" class="w3-margin-top w3-center">
                <!-- Aqui se agregaron botones -->
                <button class="w3-btn w3-red " href="{% url 'usuarios:cursos_admin_create' curso.id id.usuario.id%}">Modificar</button>
                <a class = "w3-btn w3-red"  href="{% url 'usuarios:cursos_admin_create' curso.id usuario.id %}">Modificar2</a>
                <button class="w3-btn w3-red"  href="{% url 'usuarios:cursos_admin_delete' curso.id usuario.id %}">Eliminar</button>
            </div>
        </div>

    {%  endfor %}
         <!-- Caso contrario se indica que no hay cursos-->
    {% else %}
        <p>No courses</p>
    {% endif %}


    <!--Caja de agregar-->
        <div class="w3-quarter w3-margin-top w3-center">
          <button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-light-gray w3-hover-shadow" style="min-height: 317px">
          <span style="font-size:22px">Agregar <br>curso nuevo</span>
          <i class="fas fa-plus" style="font-size:100px;text-align: center; padding:30px"></i>
          </button>
        </div>

        <div id="agregar" class="w3-modal">

        <!--
        <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
            <div class="w3-center"><br>
                <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
                <form class="w3-container" action="/action_page.php">
                <div class="w3-section">
                    <label><b>Curso</b></label>
                    <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre del curso"
                         id="course_name" name="course_name" required>

                    <label><b>Código</b></label>
                    <input class="w3-input w3-border" type="text" placeholder="Ingrese código del curso"
                         id="course_id" name="course_id" required>

                    <label><b>Sección</b></label>
                    <input class="w3-input w3-border" type="text" placeholder="Ingrese número de sección"
                         id="course_section" name="course_section" required>

                    <label><b>Año</b></label>
                    <input class="w3-input w3-border" type="text" placeholder="Ingrese año"
                         id="course_year" name="course_year" required>

                    <label for="course_semester"><b>Semestre</b></label>
                    <div class="semester">
                        <select id="course_semester" name="course_semester">
                            <option value="priv">Primavera</option>
                            <option value="oto">Otoño</option>
                        </select>
                    </div>
                    <button class="w3-button w3-block w3-red w3-section w3-padding" type="submit">Agregar</button>
                </div>
                </form>
            </div>
        <!--Cierre de cajas de cursos-->
        <!--</div>
    <!--cierre de contenido-->
<!--</div>
</div>-->
            <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
                <div class="w3-center"><br>
                    <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
                    <!-- id="nuevo_curso", nuevo curso es una variable del post, que recibio esta pagina
                     y en nuevo_curso, viene el form-->
                    <form method="post" id="nuevo_curso" enctype="multipart/form-data">

                        <!--token, sirve cuando uno deja viva la sesion -->
                        {% csrf_token %}
                        <!-- en table se muestra el form-->
                        <table class="table table-bordered">
                            <!--
                            {% for field in nuevo_curso.hidden_fields %}
                              {{ field }}
                            {% endfor %}
                            -->

                            <!-- por cada campo del form, lo pongo en el html -->
                            {% for field in nuevo_curso.visible_fields %}
                            <tr>
                                <td>{{ field.label_tag }}</td>
                                <td>{{ field }}</td>
                            </tr>
                            {% endfor %}
                        </table>
                        <!-- Boton de agregar del formulario-->
                        <button type="submit" class="btn btn-success" style="width: 100%; height: 60px; font-size: 31px; font-weight: bolder">Agregar</button>
                    </form>
                </div>
                <!--cierre de cajas de cursos-->
            </div>
        </div>
    <!--cierre de contenido-->
</div>



<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}
// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>
{% endblock page %}

templates/Usuarios/Admin/Cursos_admin_create.html
{% extends 'Usuarios/menuAdmin.html' %}
{% block page %}
    <div class="w3-main" style="margin-left:340px;margin-right:40px">
    <form method="post" id="form" enctype="multipart/form-data">
        <!--token, sirve cuando uno deja viva la sesion -->
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success" style="width: 100%; height: 60px; font-size: 31px; font-weight: bolder">Actualizar</button>
    </form>
    </div>
{% endblock %}

templates/Usuarios/Admin/Cursos_admin_delete.html
{% extends 'Usuarios/menuAdmin.html' %}
{% block page %}
    <div class="w3-main" style="margin-left:340px;margin-right:40px">
    <form method="post" id="form" enctype="multipart/form-data">
        <!--token, sirve cuando uno deja viva la sesion -->
        {% csrf_token %}
        <h3>¿Desea eliminar el curso {{ curso.nombreCurso }} {{ curso.codigoCurso }}-{{ curso.numSeccionCurso }}
            {{ curso.anioCurso }} - {{ curso.semesterCurso }} ?</h3>
        <button type="submit" class="btn btn-success" style="width: 100%; height: 60px; font-size: 31px; font-weight: bolder">Sí</button>
        <a class = "btn btn-success"  href="{% url 'usuarios:cursos_admin' usuario.id %}">No</a>
    </form>
    </div>
{% endblock %}

templates/Usuarios/Admin/Evaluadores_admin_delete.html
{% extends 'Usuarios/menuAdmin.html' %}
{% block page %}
    <div class="w3-main" style="margin-left:340px;margin-right:40px">
    <form method="post" id="form" enctype="multipart/form-data">
        <!--token, sirve cuando uno deja viva la sesion -->
        {% csrf_token %}
        <h3>¿Desea eliminar al evaluador {{ eval.name }} {{ eval.app_paterno }} {{ eval.app_materno }}?</h3>
        <button type="submit" class="btn btn-success" style="width: 100%; height: 60px; font-size: 31px; font-weight: bolder">Sí</button>
        <a class = "btn btn-success"  href="{% url 'usuarios:evaluadores_admin' usuario.id %}">No</a>
    </form>
    </div>
{% endblock %}

templates/Usuarios/Admin/Rubricas_admin.html
{% extends 'Usuarios/menuAdmin.html' %}
{%block page%}
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Rúbricas</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>

<div class="w3-container">
  <a class="w3-button w3-large w3-red w3-right w3-round" href="{% url 'usuarios:rubricas_admin_create' usuario.id%}" >Agregar nueva rúbrica</a><br>
</div>

<!--Seccion rubricas-->
  {%for i in rubricsNames%}
  <button onclick="myFunction()" class="w3-btn w3-red w3-block w3-margin" style="width: 75%"><h3>
    {{i}}</h3></button>

  <div id={{i}} class="show w3-container w3-pale-red w3-center w3-padding-large w3-margin"style="width: 75%">
  <p><li>Aspecto 1</li>
    <li>Aspecto 2</li>
</p>
    <div class="w3-container">
      <a class="w3-button w3-large w3-margin-right w3-red w3-left w3-round" href="{% url 'usuarios:rubricas_admin_ver' usuario.id i%}">Ver</a>
  <a class="w3-button w3-large w3-red w3-left w3-round">Modificar</a>
  <a class="w3-button w3-large w3-red w3-right w3-round" href="{% url 'usuarios:rubricas_admin_eliminar' usuario.id i%}">Eliminar</a>
</div>
</div>


  {%endfor%}




</div>
<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
{%endblock page%}