Usuarios/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('landing_admin/<int:usuario_id>/<int:isAdmin>/', views.menu, name='landing_admin'),

    path('cursos_admin/<int:usuario_id>/', views.cursos_admin, name='cursos_admin'),

    path('cursos_admin_create/<int:usuario_id>/<int:id_curso>/', views.cursos_admin_create, name='cursos_admin_create'),
    path('cursos_admin_delete/<int:usuario_id>/<int:id_curso>/', views.cursos_admin_delete, name='cursos_admin_delete'),
    path('evaluaciones_admin/<int:usuario_id>/<int:isAdmin>/', views.evaluaciones_admin, name='evaluaciones_admin'),
    path('evaluaciones_admin_ver/<int:usuario_id>/<str:rubrica_name>/<int:isAdmin>/', views.evaluaciones_admin_ver,
         name='evaluaciones_admin_ver'),

    path('evaluaciones_admin_create/<int:usuario_id>/', views.evaluaciones_admin_create, name='evaluaciones_admin_create'),
    path('evaluadores_admin/<int:usuario_id>/', views.evaluadores_admin, name='evaluadores_admin'),

    path('evaluadores_admin_edit/<int:usuario_id>/<int:eval_id>/', views.evaluadores_admin_edit, name='evaluadores_admin_edit'),
    path('evaluadores_admin_delete/<int:usuario_id>/<int:eval_id>/', views.evaluadores_admin_delete, name='evaluadores_admin_delete'),

    path('rubricas_admin/<int:usuario_id>/', views.rubricas_admin, name='rubricas_admin'),
    path('rubricas_admin_create/<int:usuario_id>/', views.rubricas_admin_create, name='rubricas_admin_create'),
    path('rubricas_admin_ver/<int:usuario_id>/<str:rubricaName>', views.rubricas_admin_ver, name='rubricas_admin_ver'),

    path('rubricas_admin_eliminar/<int:usuario_id>/<str:rubricaName>', views.rubricas_admin_eliminar, name='rubricas_admin_eliminar'),

    # para registrarse
    path('registro/', views.registro, name='registro'),
]

swjjRubricas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(('Usuarios.urls', 'Usuarios'), namespace='usuarios')),
    path('admin/', admin.site.urls),
]

Usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Usuario_admin(models.Model):
    name = models.CharField(max_length=200)
    app_paterno = models.CharField(max_length=50, blank=True, null=True)
    app_materno = models.CharField(max_length=50, blank=True, null=True)
    isAdmin = models.BooleanField(default=True)
    password = models.CharField(max_length=50)

class Usuario_evaluador(models.Model):
    name = models.CharField(max_length=200)
    app_paterno = models.CharField(max_length=50, blank=True, null=True)
    app_materno = models.CharField(max_length=50, blank=True, null=True)
    correo = models.EmailField(max_length=100)
    isAdmin = models.BooleanField(default=False)
    password = models.CharField(max_length=50) # TODO : Remember to randomize
    myAdminID = models.ForeignKey(Usuario_admin,on_delete=models.CASCADE)

    class Meta:
        unique_together = ('correo',)

    def __str__(self):
        return self.name

class Course(models.Model):
    nombreCurso = models.CharField(max_length=250, help_text='Nombre del curso ')
    codigoCurso = models.CharField(max_length=8, help_text='Codigo curso ')
    numSeccionCurso = models.IntegerField(help_text='Numero seccion del curso')
    anioCurso = models.IntegerField(help_text='Año del curso ')
    semesterCurso = models.IntegerField(help_text='Semestre ')

    class Meta:
        unique_together = ('codigoCurso', 'numSeccionCurso', 'anioCurso' ,'semesterCurso',)

    def __str__(self):
        return self.nombreCurso

class Grupo(models.Model):
    nombreGrupo = models.CharField(max_length=200)
    cursoGrupo = models.ForeignKey(Course,on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreGrupo

class Alumno(models.Model):
    nombreAlumno = models.CharField(max_length=200)
    hasPresented = models.BooleanField(default=False) # Agregado
    grupoAsociado = models.ForeignKey(Grupo,on_delete=models.DO_NOTHING) # TODO: Es buena idea doNothing?
    cursoAsociado = models.ForeignKey(Course,on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreAlumno

class Rubrica(models.Model):
    nombre: object = models.CharField(max_length=100)
    duracion_minima = models.TimeField(u"Duración Mínima")
    duracion_maxima = models.TimeField(u"Duración Máxima")
    dataTable = models.FilePathField(path='./RubricasDataTables')


    def __str__(self):
        return self.nombre

    def get_criterios(self):
        """
        Gets all criterios of this rubrica
        :return: a list of Criterio
        """
        return Criterio.objects.filter(rubrica__nombre=self.nombre)

class Evaluacion(models.Model):
    nombre: object = models.CharField(max_length=100)
    curso = models.ForeignKey(Course,on_delete=models.CASCADE)
    equipo = models.ForeignKey(Grupo,on_delete=models.CASCADE) # TODO : Deberia ser do nothing
    rubrica = models.ForeignKey(Rubrica,on_delete=models.CASCADE)
    # evaluadores = models.ManyToManyField(Usuario_evaluador, null=True) # NOT NULL constraint failed

    def __str__(self):
        return self.nombre

class EvaluacionAsignada(models.Model):
    evaluador = models.ManyToManyField(Usuario_evaluador)


class Criterio(models.Model):
    rubrica = models.ForeignKey(Rubrica, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    def get_puntajes(self):
        """
        Gets all puntaje that belong to this criterio
        :return: a list of Puntaje
        """
        return Puntaje.objects.filters(criterio__nombre=self.nombre)


class Puntaje(models.Model):
    criterio = models.ForeignKey(Criterio, on_delete=models.CASCADE)
    puntaje = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    texto = models.CharField(max_length=200)

    def __str__(self):
        return self.texto

Usuarios/views.py
from django.shortcuts import render

# tal vez deba borrar algunas de estas
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import redirect # Added
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
##

# formularios

from .forms import RegistroUsuarioForm, RegistroEvaluadorForm, NuevaEvaluacion
from .forms import NuevoCurso
from .forms import NuevoEvaluador
from .forms import NuevaRubrica
##
from .models import Usuario_admin, Course, Rubrica, Criterio, Puntaje, Usuario_evaluador
import csv

##para el json
import json


##
def login(request):
    if request.POST:
        username = request.POST.get('usuario')
        password = request.POST.get('password')

        # Verificar si es admin
        if (Usuario_admin.objects.filter(name=username, password=password).exists()):
            user = Usuario_admin.objects.get(name=username, password=password)
            return menu(request,user.id,user.isAdmin)

        if (Usuario_evaluador.objects.filter(correo=username, password=password).exists()):
            user = Usuario_evaluador.objects.get(correo=username, password=password)
            return menu(request,user.id,user.isAdmin)

    return render(request, 'Usuarios/login.html')


def courses(request):
    listaCursos = Course.objects.all()
    return listaCursos


def menu(request, usuario_id,isAdmin):
    # aca deberia haccerse la autenticaciondel usuario.
    if isAdmin==1:
        usuario = Usuario_admin.objects.get(pk=usuario_id)
    else:
        usuario= Usuario_evaluador.objects.get(pk=usuario_id)

    return render(request, 'Usuarios/Admin/Landing_admin.html', {'usuario': usuario})


def cursos_admin(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)

    if request.POST:
        form = NuevoCurso(request.POST, request.FILES)
        if form.is_valid():  # si no no crea los cleaned data
            form.save()

    listaCursos = courses(request)
    form = NuevoCurso()

    # le paso el form, nuevo_curso a la página.
    return render(request, 'Usuarios/Admin/Cursos_admin.html',
                  {'usuario': usuario, 'nuevo_curso': form, 'listaCursos': listaCursos})

# TODO : Se encarga de editar o realizar update, ignorar nombre
def cursos_admin_create(request, usuario_id, id_curso):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    curso = Course.objects.get(id=id_curso)
    if request.method == 'GET':
        form = NuevoCurso(instance=curso)
    else:
        form = NuevoCurso(request.POST, request.FILES ,instance=curso)
        if form.is_valid():
            form.save()
        #return redirect('usuarios:cursos_admin', {'usuario' : usuario})
        # SOL : https://stackoverflow.com/questions/13202385/django-reverse-with-arguments-and-keyword-arguments-not-found
        return redirect(reverse('usuarios:cursos_admin',kwargs={'usuario_id' : usuario_id})) # Funciona
    return render(request,'Usuarios/Admin/Cursos_admin_create.html',{'form' : form, 'usuario': usuario, 'curso': curso})

def cursos_admin_delete(request, usuario_id, id_curso):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    curso = Course.objects.get(id = id_curso)
    if request.method == 'POST':
        curso.delete()
        #return redirect('usuarios:cursos_admin')
        return redirect(reverse('usuarios:cursos_admin', kwargs={'usuario_id': usuario_id})) # Funciona
    return render(request, 'Usuarios/Admin/Cursos_admin_delete.html', {'usuario': usuario ,'curso' : curso})

def evaluaciones_admin(request, usuario_id,isAdmin):
    if isAdmin==1:
        usuario = Usuario_admin.objects.get(pk=usuario_id)
    else:
        usuario = Usuario_evaluador.objects.get(pk=usuario_id)



    #esta parte esta harcodeada, pero se deberia arreglar, cuando el modelo Evaluacion este listo
    listaEval = []
    listaEval.append("tarea1")
    listaEval.append("tarea2")




    return render(request, 'Usuarios/Admin/Evaluaciones_admin.html', {'usuario': usuario,'listaEval':listaEval})


def evaluaciones_admin_ver(request, usuario_id,rubrica_name, isAdmin):
    if isAdmin == 1:
        usuario = Usuario_admin.objects.get(pk=usuario_id)

        with open('rubricaJson.json', 'r') as f:
            data = json.load(f)

        if data:
            if str(usuario_id) in data:
                j = data[str(usuario_id)][rubrica_name]
                matriz = parseJsonToMatriz(j, int(j.get("numFilas")), int(j.get("numColumnas")))
                print(j.get("numColumnas"))

    else:
        usuario = Usuario_evaluador.objects.get(pk=usuario_id)

        with open('rubricaJson.json', 'r') as f:
            data = json.load(f)

        if data:
            if str(usuario.myAdminID.id) in data:
                j = data[str(usuario.myAdminID.id)][rubrica_name]
                matriz = parseJsonToMatriz(j, int(j.get("numFilas")), int(j.get("numColumnas")))
                print(j.get("numColumnas"))

    return render(request, 'Usuarios/Admin/Evaluaciones_admin_ver.html', {'usuario': usuario,'rubrica':j,'matriz':matriz,'rangeCol':range(int(j.get("numColumnas"))-1)})


def evaluaciones_admin_create(request, usuario_id): # TODO: Complete
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    if request.POST:
        form = NuevaEvaluacion(request.POST, request.FILES)
        if form.is_valid():
            # listaDeEvaluadores = form.cleaned_data.get('evaluadores')
            form.save()
    form = NuevaEvaluacion()
    return render(request, 'Usuarios/Admin/Evaluaciones_admin_create.html', {'usuario': usuario, 'nueva_eval': form})


def evaluadoresReq(request):
    listaEvaluadores = Usuario_evaluador.objects.all()
    return listaEvaluadores


def evaluadores_admin(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)

    if request.POST:
        form = RegistroEvaluadorForm(request.POST, request.FILES)
        if form.is_valid():  # si no no crea los cleaned data
            form.save(usuario_id)  # por el override, ver forms

    listaEvaluadores = evaluadoresReq(request)
    form = RegistroEvaluadorForm()

    # le paso el form, nuevo_curso a la página.
    return render(request, 'Usuarios/Admin/Evaluadores_admin.html', {'usuario': usuario, 'nuevo_evaluador': form,
                                                                     'listaEval': listaEvaluadores})


#def evaluadores_admin_edit(request, usuario_id):
#    usuario = Usuario_admin.objects.get(pk=usuario_id)
#    return render(request, 'Usuarios/Admin/Evaluadores_admin_edit.html', {'usuario': usuario})

def evaluadores_admin_edit(request, usuario_id, eval_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    evaluador = Usuario_evaluador.objects.get(id=eval_id)
    if request.method == 'GET':
        form = RegistroEvaluadorForm(instance=evaluador)
    else:
        form = RegistroEvaluadorForm(request.POST, request.FILES ,instance=evaluador)
        if form.is_valid():
            form.save(usuario_id, evaluador) # Literalmente envia el objeto
        #return redirect('usuarios:cursos_admin', {'usuario' : usuario})
        # SOL : https://stackoverflow.com/questions/13202385/django-reverse-with-arguments-and-keyword-arguments-not-found
        return redirect(reverse('usuarios:evaluadores_admin',kwargs={'usuario_id' : usuario_id})) # Funciona
    return render(request,'Usuarios/Admin/Evaluadores_admin_edit.html',{'form' : form, 'usuario': usuario, 'eval': evaluador})


#def evaluadores_admin_delete(request, usuario_id):
#    usuario = Usuario_admin.objects.get(pk=usuario_id)
#    return render(request, 'Usuarios/Admin/Evaluadores_admin_delete.html', {'usuario': usuario})

def evaluadores_admin_delete(request, usuario_id, eval_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    evaluador = Usuario_evaluador.objects.get(id=eval_id)
    if request.method == 'POST':
        evaluador.delete()
        #return redirect('usuarios:cursos_admin')
        return redirect(reverse('usuarios:evaluadores_admin',kwargs={'usuario_id' : usuario_id})) # Funciona
    return render(request, 'Usuarios/Admin/Evaluadores_admin_delete.html', {'usuario': usuario ,'eval': evaluador})


# Commit 15.05

def rubricas_admin(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)

    # Primero que nada, guardar una nueva rubrica
    if request.POST:
        form = NuevaRubrica(request.POST, request.FILES)

        new_rubrica = form.save(request.POST, usuario_id)
        print("rubrica guardada con exito")

    with open('rubricaJson.json', 'r') as f:
        data = json.load(f)


    rubricsNames = []
    if data:
        if str(usuario_id) in data:
            for key in data[str(usuario_id)]:
                rubricsNames.append(key)
    print(rubricsNames)

    return render(request, 'Usuarios/Admin/Rubricas_admin.html', {'usuario': usuario, 'rubricsNames': rubricsNames})


def rubricas_admin_create(request, usuario_id):
    usuario = Usuario_admin.objects.get(pk=usuario_id)
    # Esta es
#   Esto ahora se encuentra en rubricas_admin
#    if request.POST:
#        form = NuevaRubrica(request.POST, request.FILES)#
#
#        if form.is_valid():
#           new_rubrica = form.save(request.POST, usuario_id)
#            print("rubrica guardada con exito")
#        else:
#            print("Hay datos incorrectos")
#            return render(request, 'Usuarios/Admin/Rubricas_admin_create.html', {'usuario': usuario, 'nueva_rubrica': form})

    form = NuevaRubrica()

    return render(request, 'Usuarios/Admin/Rubricas_admin_create.html', {'usuario': usuario, 'nueva_rubrica': form})


# para el registro
def registro(request):
    if request.POST:
        form = RegistroUsuarioForm(request.POST, request.FILES)

        if form.is_valid():
            new_admin = form.save()
            return menu(request, new_admin.id, new_admin.isAdmin)

templates/Usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.1.3/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap-4.1.3/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.5.0/css/all.min.css' %}">
    <script src="{% static 'fontawesome-free-5.5.0/js/fontawesome.min.js' %}"></script>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    {% block extracss %} {% endblock extracss %}
</head>
<body>
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{% url 'Usuarios:login' %}">Rubricas</a>

    <!--trucaso: sirve para separar el login de rubricas-->
    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
      </div>
    </form>

    <!-- Navbar -->
      <a class="navbar-brand mr-1" href="{% url 'Usuarios:login' %}">Rubricas</a>
  </nav>



  <div>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" style="text-align: center;">Iniciar Sesión</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            <form action="{% url 'usuarios:login' %}" method="post" id="login_form">
              {% csrf_token %}
              <div class="form-group has-feedback">
                  <input name="usuario" class="form-control" placeholder="Nombre de usuario" type="text" required>
                  <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
              </div>
              <div class="form-group has-feedback">
                  <input name="password" class="form-control" placeholder="Contraseña" type="password" required>
                  <span class="glyphicon glyphicon-lock form-control-feedback"></span>
              </div>
            </form>

        </div>
        <div class="modal-footer">

            <button type="button" class="btn btn-danger" style="float: left" data-dismiss="modal">Cerrar</button>
            <a class="btn btn-primary" href="{% url 'usuarios:registro' %}">Registrarse</a>
            <button type="button" class="btn btn-success" onclick="$('#login_form').submit()">Login</button>

        </div>
      </div>
    </div>
  </div>

  <!-- esta es la imagen -->
  <!--{% block frame %} {% endblock frame %}-->

  {% block extrajs %} {% endblock extrajs %}

</body>

</html>

templates/Usuarios/menuAdmin.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="es">
<!-- bootstrap-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="stylesheet" href="{% static 'bootstrap-4.1.3/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap-4.1.3/js/bootstrap.bundle.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'fontawesome-free-5.5.0/css/all.min.css' %}">
<script src="{% static 'fontawesome-free-5.5.0/js/fontawesome.min.js' %}"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!--bootstrap-->




<title>Plataforma de evaluación</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">✖</a>
    <!-- Profile image -->
  <div class="w3-container">
      <p class="w3-center"><img src="https://www.w3schools.com/w3images/avatar2.png" class="w3-circle" style="height:150px" alt="Avatar"></p>
    <h3 class="w3-padding-47"><center><b>{{ usuario.name }}</b></center></h3>
  </div>
  <!-- Menu options -->
  <div class="w3-bar-block">
<<<<<<< HEAD
    {%if usuario.isAdmin %}
    <a href="{% url 'usuarios:landing_admin' usuario.id 1%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    <a href="{% url 'usuarios:evaluaciones_admin' usuario.id 1%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
=======
    <br>
    <a href="{% url 'usuarios:landing_admin' usuario.id%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
>>>>>>> remotes/origin/devSofia
    <a href="{% url 'usuarios:cursos_admin' usuario.id%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>
    <a href="{% url 'usuarios:evaluadores_admin' usuario.id%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
    <a href="{% url 'usuarios:rubricas_admin' usuario.id %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a>
    <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>
    {%else%}
    <a href="{% url 'usuarios:landing_admin' usuario.id 0%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    <a href="{% url 'usuarios:evaluaciones_admin' usuario.id 0%}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>

    {%endif%}
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Usuario</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>



{% block page %} {% endblock page %}



<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>